stages:
  - build
  - deploy
build_job:
  image: node:alpine
  stage: build
  only:
    - master
  before_script:
    - echo "Installing NPM Dependencies and building React app"
  script:
    - npm install
    - killall node > /dev/null || true
    - CI=false npm run build
  tags:
    - telehealth_frontend
  after_script:
    - echo "Installation and build successfull"
  cache:
    key: install-cache
    paths:
      - node_modules/
  artifacts:
    paths:
      - build/
  when: manual
  
deploy_job:
  stage: deploy
  image: google/cloud-sdk:alpine
  only:
  - development
  - master
  - ci-cd
  tags:
  - telehealth_frontend
  before_script:
  - "ServiceName=telehealth"
  - "echo $ServiceName"
  - |
    cat <<EOF >> app.yaml
    runtime: nodejs14
    service: $ServiceName
    handlers:
    # Serve all static files with url ending with a file extension
    - url: /(.*\..+)$
      static_files: build/\1
      upload: build/(.*\..+)$
    # Catch all handler to index.html
    - url: /.*
      static_files: build/index.html
      upload: build/index.html
    instance_class: B1
    manual_scaling:
      instances: 1

    EOF

  - "cat app.yaml"
  - echo $GCP_SERVICE_CRED > ${CI_PIPELINE_ID}.json

  script:

  - gcloud auth activate-service-account --key-file $CI_PIPELINE_ID.json
  - gcloud --project hu18-groupa-java app deploy --version v1 --appyaml app.yaml
  - url=$(gcloud app services browse $ServiceName --no-launch-browser --project hu18-groupa-java)
  - echo $url

  after_script:
  - rm $CI_PIPELINE_ID.json
  when: manual