# Generated by Django 3.2.3 on 2021-05-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_specialization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
    ]
