# Generated by Django 3.2.3 on 2021-06-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
