# Generated by Django 3.2.3 on 2021-06-07 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=60, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Only 10 digits allowed.", regex='^\\+?1?\\d{10,10}$')]),
        ),
    ]
