# Generated by Django 3.2.3 on 2021-05-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_auto_20210531_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='employement',
            new_name='employment',
        ),
    ]
