# Generated by Django 3.2.3 on 2021-06-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_auto_20210602_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='number',
            new_name='contact',
        ),
    ]
