# Generated by Django 3.2.3 on 2021-06-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_rename_number_patientprofile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='email',
        ),
    ]
