# Generated by Django 3.2.3 on 2021-06-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_remove_patientprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='contact',
        ),
    ]
