# Generated by Django 3.2.3 on 2021-06-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_alter_patientprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='users/profileimage'),
        ),
    ]
