# Generated by Django 3.2.3 on 2021-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0010_alter_patientprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='dob',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
