# Generated by Django 3.2.3 on 2021-06-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0011_alter_patientprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='dob',
            field=models.DateField(max_length=8),
        ),
    ]
