# Generated by Django 3.2.3 on 2021-06-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_auto_20210623_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
    ]
